[package]
name = "mathgen"
version = "0.1.0"
authors = ["Sian Cao <yinshuiboy@gmail.com>"]
edition = "2018"

[dependencies]
cairo-rs = {version = "0.6", features = ["png", "pdf"]}
rand = "0.6"
env_logger = "0.5"
log = "0.4"

